FROM node:20-alpine AS builder
WORKDIR /app
COPY . .
# Build du front [cite: 79]
RUN npm install && npm run build

FROM nginx:1.27-alpine AS runtime
COPY --from=builder /app/dist/ /usr/share/nginx/html/
EXPOSE 80
# Healthcheck Nginx [cite: 83]
HEALTHCHECK --interval=30s --timeout=5s CMD wget -qO- http://127.0.0.1/health || exit 1
