# Service User
[cite_start]apiVersion: apps/v1 [cite: 131]
[cite_start]kind: Deployment [cite: 132]
metadata:
  [cite_start]name: service-user [cite: 134]
spec:
  [cite_start]replicas: 1 [cite: 136]
  selector:
    matchLabels:
      [cite_start]app: service-user [cite: 139]
  template:
    metadata:
      labels:
        [cite_start]app: service-user [cite: 143]
    spec:
      containers:
      - [cite_start]name: service-user [cite: 146]
        [cite_start]image: user-service:latest [cite: 147]
        imagePullPolicy: Never # Pour utiliser l'image locale
        ports:
        - [cite_start]containerPort: 5001 [cite: 149]
---
# Service Order
[cite_start]apiVersion: apps/v1 [cite: 150]
[cite_start]kind: Deployment [cite: 151]
metadata:
  [cite_start]name: service-order [cite: 153]
spec:
  [cite_start]replicas: 1 [cite: 155]
  selector:
    matchLabels:
      [cite_start]app: service-order [cite: 158]
  template:
    metadata:
      labels:
        [cite_start]app: service-order [cite: 162]
    spec:
      containers:
      - [cite_start]name: service-order [cite: 165]
        [cite_start]image: order-service:latest [cite: 166]
        imagePullPolicy: Never
        ports:
        - [cite_start]containerPort: 5002 [cite: 168]